/** Adapted from satnaing/shadcn-admin e16c87f (MIT, Sat Naing 2024): authenticated layout, nav groups, theme provider, OTP/form/dialog patterns. */
import React, { FormEvent, useCallback, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { api, getContract, type LegacyStatus } from './client'
import { ConfirmDialog, NavGroup, OtpForm, ThemeSwitch, Sheet, SheetPortal, SheetOverlay, SheetContent, SheetClose, AlertDialog, AlertDialogTrigger, AlertDialogPortal, AlertDialogOverlay, AlertDialogContent, AlertDialogTitle, AlertDialogCancel, AlertDialogAction } from './shadcn-admin-adapted'
import './styles.css'
import { resolveLocale, storageKey } from '../../i18n/i18n.mjs'
import { RecordingWorkbench } from './recordings'

type Language = 'en'|'zh-CN'; const validSection=(p:string)=>{const x=p.replace(/^\/app\/?/,'').split('/')[0];return ['recordings','live','jobs','settings'].includes(x)?x:'recordings'}; const copy = { en: { recordings:'Recordings', live:'Live', jobs:'Jobs', settings:'Settings', assistant:'Assistant', signIn:'Sign in', email:'Email', password:'Password', country:'Country', verify:'Verify email code', code:'Verification code', refresh:'Refresh inventory', logout:'Sign out', unavailable:'This area is unavailable in M1. It does not simulate functionality.', status:'Resident session', light:'Light', dark:'Dark', language:'Language', close:'Close', nav:'Primary navigation', menu:'Open navigation', captcha:'CAPTCHA challenge', codeHelp:'Enter the current verification code.', connected:'Connected', devices:'devices', confirmLogout:'End the resident session?', needLogin:'Sign in to the resident to browse its inventory.' }, 'zh-CN': { recordings:'录像', live:'实时预览', jobs:'任务', settings:'设置', assistant:'助手', signIn:'登录', email:'邮箱', password:'密码', country:'国家', verify:'验证邮件验证码', code:'验证码', refresh:'刷新设备', logout:'登出', unavailable:'此区域在 M1 中不可用，未模拟功能。', status:'本地服务会话', light:'浅色', dark:'深色', language:'语言', close:'关闭', nav:'主导航', menu:'打开导航', captcha:'图片验证码', codeHelp:'请输入当前验证码。', connected:'已连接', devices:'台设备', confirmLogout:'结束本地服务会话？', needLogin:'请登录本地服务后浏览设备清单。' } } as const
function preference(){let saved;try{saved=window.localStorage.getItem(storageKey)}catch{}return ['en','zh-CN'].includes(saved)?saved:'auto'}
function currentLocale(pref:string){return resolveLocale(pref,navigator.languages?.length?navigator.languages:[navigator.language]) as Language}
function Sidebar({t,section,navigate,assistant}:{t:any;section:string;navigate:(x:string)=>void;assistant:(el:HTMLButtonElement)=>void}){return <><div className="brand">Eufy Agent Hub</div><NavGroup label={t.nav} active={section} onNavigate={navigate} items={(['recordings','live','jobs','settings'] as const).map(id=>({id,label:t[id]}))}/><button className="assistant" onClick={e=>assistant(e.currentTarget)}>{t.assistant}</button></>}
const LogoutDialog=React.memo(function LogoutDialog({busy,onConfirm,t}:{busy:boolean;onConfirm:()=>void;t:any}){return <AlertDialog><AlertDialogTrigger asChild><button className="danger" disabled={busy}>{t.logout}</button></AlertDialogTrigger><AlertDialogPortal><AlertDialogOverlay className="drawer-overlay"/><AlertDialogContent className="drawer"><div><AlertDialogTitle asChild><h2>{t.logout}</h2></AlertDialogTitle><p>{t.confirmLogout}</p><AlertDialogCancel asChild><button>{t.close}</button></AlertDialogCancel><AlertDialogAction asChild><button onClick={onConfirm}>{t.logout}</button></AlertDialogAction></div></AlertDialogContent></AlertDialogPortal></AlertDialog>})
function App() { const menuRef=useRef<HTMLButtonElement>(null); const [catalog,setCatalog]=useState<Record<string,string>>({}); const [status,setStatus]=useState<LegacyStatus>(); const [error,setError]=useState(''); const [unreachable,setUnreachable]=useState(false); const [languagePreference,setLanguagePreference]=useState(preference); const [language,setLanguage]=useState<Language>(()=>currentLocale(preference())); const [dark,setDark]=useState(()=>{try{return localStorage.getItem('eufy-agent-hub.theme')==='dark'}catch{return false}}); const [section,setSection]=useState(()=>validSection(location.pathname)); const [open,setOpen]=useState(false); const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(()=>matchMedia('(max-width:700px)').matches); const [assistant,setAssistant]=useState(false); const assistantReturnRef=useRef<HTMLElement|null>(null); const t=copy[language]; const resolve=(raw?:string,meta?:any)=>meta?.key ? (catalog[meta.key]||raw||meta.key).replace(/\{(\w+)\}/g,(_:string,k:string)=>String(meta.params?.[k]??'')) : raw||'';
  const poll=async()=>{ try { await getContract(); const next=await api.status(); setStatus(next); setUnreachable(false) } catch { setUnreachable(true) } };
  useEffect(()=>{const update=()=>{if(languagePreference==='auto')setLanguage(currentLocale('auto'))};addEventListener('languagechange',update);return()=>removeEventListener('languagechange',update)},[languagePreference]); useEffect(()=>{document.documentElement.lang=language},[language]); useEffect(()=>{const m=matchMedia('(max-width:700px)'),h=()=>setMobile(m.matches);m.addEventListener('change',h);return()=>m.removeEventListener('change',h)},[]); useEffect(()=>{fetch(`/locales/${language}.json`).then(r=>r.json()).then(setCatalog).catch(()=>setCatalog({}))},[language]); useEffect(()=>{ poll(); const id=setInterval(poll,1200); const pop=()=>setSection(validSection(location.pathname)); addEventListener('popstate',pop); return()=>{clearInterval(id);removeEventListener('popstate',pop)} },[]); useEffect(()=>{ document.documentElement.classList.toggle('dark',dark); try{localStorage.setItem('eufy-agent-hub.theme',dark?'dark':'light')}catch{} },[dark]);
  const action=useCallback(async (fn:()=>Promise<unknown>)=>{setError('');try{await fn();await poll()}catch(e:any){const code=e.body?.error?.code;setError(code?(catalog['ui.error.'+code]||catalog['ui.error.busy']||e.body?.error?.message):e.body?.error?.message||e.message||'Request failed');await poll()}},[catalog]);
  const login=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const d=new FormData(e.currentTarget); action(()=>api.login(String(d.get('email')),String(d.get('password')),String(d.get('country')))); e.currentTarget.reset()};
  const verify=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const d=new FormData(e.currentTarget); action(()=>api.verify(String(d.get('code')))); e.currentTarget.reset()};
  const confirmLogout=useCallback(()=>action(api.logout),[action]); const message=error || (unreachable ? (language==='en'?'The local resident is unreachable.':'无法连接本地服务。') : '') || resolve(status?.message,status?.messageI18n) || (!status?.authenticated?t.needLogin:''); const navigate=(id:string)=>{history.pushState({},'',`/app/${id}`);setSection(id);setOpen(false)};
  return <div className="shell"><a className="skip" href="#main">{language==='en'?'Skip to content':'跳至内容'}</a>{mobile?<Sheet open={open} onOpenChange={setOpen}><SheetPortal><SheetOverlay className="sheet-overlay"/><SheetContent className="sidebar open sheet-sidebar" aria-label={t.nav} onCloseAutoFocus={event=>{event.preventDefault();menuRef.current?.focus()}}><SheetClose asChild><button className="sheet-close">{t.close}</button></SheetClose><Sidebar t={t} section={section} navigate={navigate} assistant={()=>{assistantReturnRef.current=menuRef.current;setOpen(false);setAssistant(true)}}/></SheetContent></SheetPortal></Sheet>:<aside className={`sidebar ${collapsed?'collapsed':''}`} aria-label={t.nav}><Sidebar t={t} section={section} navigate={navigate} assistant={el=>{assistantReturnRef.current=el;setAssistant(true)}}/></aside>}<div className="content"><header><button className="collapse" aria-label={t.menu} aria-pressed={collapsed} onClick={()=>setCollapsed(!collapsed)}>◀</button><button ref={menuRef} className="menu" aria-label={t.menu} onClick={()=>setOpen(!open)}>☰</button><strong>{t[section as keyof typeof t] || t.recordings}</strong><div className="controls"><select aria-label={t.language} value={languagePreference} onChange={e=>{const v=e.target.value;setLanguagePreference(v);setLanguage(currentLocale(v));try{localStorage.setItem(storageKey,v)}catch{}}}><option value="auto">{language==='en'?'Follow browser':'跟随浏览器'}</option><option value="en">EN</option><option value="zh-CN">中文</option></select><ThemeSwitch dark={dark} onToggle={()=>setDark(!dark)} label={dark?t.light:t.dark}/></div></header><main id="main"><p className="eyebrow">{t.status}</p><h1>{status?.authenticated ? (status.devices?.length ? `${status.devices.length} ${t.devices}` : t.connected) : t.signIn}</h1>{message&&<div role="status" className="notice">{message}</div>}{status?.diagnostics?.length ? <ul className="diagnostics">{status.diagnostics.map((d,i)=><li key={i}>{resolve(d,status.diagnosticsI18n?.[i])}</li>)}</ul>:null}
  {section==='recordings' ? <><Auth status={{...status,message:resolve(status?.message,status?.messageI18n)}} t={t} login={login} verify={verify} action={action} logoutControl={<LogoutDialog busy={status?.busy} onConfirm={confirmLogout} t={t}/>} /><RecordingWorkbench authenticated={Boolean(status?.authenticated)} language={language} catalog={catalog} inventoryKey={JSON.stringify(status?.devices||[])}/></> : <section className="card"><h2>{t[section as keyof typeof t]}</h2><p>{t.unavailable}</p></section>}</main></div><ConfirmDialog open={assistant} title={t.assistant} closeLabel={t.close} close={()=>setAssistant(false)} returnFocusRef={assistantReturnRef}><p>{t.unavailable}</p></ConfirmDialog></div> }
function Auth({status,t,login,verify,action,logoutControl}:any) { if(status?.authenticated) return <section className="card"><h2>{t.status}</h2><p>{status.message}</p><button onClick={()=>action(api.refresh)} disabled={status.busy}>{t.refresh}</button>{logoutControl}</section>; if(['tfa','captcha'].includes(status?.phase)) return <section className="card"><h2>{t.verify}</h2>{status.phase==='captcha'&&status.captcha?<img className="captcha" alt={t.captcha} src={status.captcha}/>:null}<OtpForm label={t.code} busy={status.busy} help={t.codeHelp} onSubmit={(code:string)=>action(()=>api.verify(code))}/><button className="link" onClick={()=>action(api.logout)}>{t.logout}</button></section>; return <section className="card"><form onSubmit={login}><label>{t.email}<input name="email" type="email" autoComplete="username" required /></label><label>{t.password}<input name="password" type="password" autoComplete="current-password" required /></label><label>{t.country}<input name="country" defaultValue="CA" pattern="[A-Za-z]{2}" required /></label><button disabled={status?.busy}>{t.signIn}</button></form></section> }
createRoot(document.getElementById('root')!).render(<App />)
