const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require('@playwright/test'); const {createServer}=require('../server.cjs');
test('Chromium M1 shell uses the resident fixture without persistence or route interception',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'eufy-pw-'));let logins=0;const session={authenticated:false,state:{phase:'login_required',devices:[],diagnostics:[],message:'请登录'},isAuthenticated(){return this.authenticated},async restore(){this.state={phase:'login_required',devices:[],diagnostics:[],message:'登录已过期，请重新登录。',messageI18n:{key:'service.auth.expired'}}},async login(d){logins++;if(d.email==='fail@test')throw new Error('login failed');this.state={phase:'tfa',devices:[],diagnostics:[],message:'验证码已发送',messageI18n:{key:'service.auth.codeSent'}}},async verify(c){if(c==='captcha'){this.state={phase:'captcha',captcha:'data:image/png;base64,iVBORw0KGgo=',devices:[],diagnostics:[],message:'请输入图片验证码'};return}if(c==='bad'){this.state={phase:'tfa',devices:[],diagnostics:[],message:'验证码不正确',messageI18n:{key:'service.auth.codeIncorrect'}};return}this.authenticated=true;this.state={phase:'connected',devices:[{serial:'fixture'}],diagnostics:[],message:'已登录',messageI18n:{key:'service.devices.loaded',params:{country:'CA',count:1}}}},async refresh(){this.state={...this.state,diagnostics:['inventory'],diagnosticsI18n:[{key:'service.devices.loadFailed',params:{country:'CA'}}],message:'读取失败',messageI18n:{key:'service.devices.loadFailed',params:{country:'CA'}}};return},fail(){this.state={phase:'login_required',devices:[],diagnostics:[],message:'登录失败',messageI18n:{key:'service.auth.loginFailed'}}},logout(){this.authenticated=false;this.state={phase:'login_required',devices:[],diagnostics:[],message:'已登出'}},close(){}};const srv=createServer({port:0,session,recordings:{close(){}},outputRoot:root});
  await new Promise(r=>srv.start(r));const origin=`http://127.0.0.1:${srv.address().port}`;let browser;t.after(async()=>{if(browser)await browser.close();
  await new Promise(r=>srv.close(r));
  await srv.shutdown();fs.rmSync(root,{recursive:true,force:true})});browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const logs=[];page.on('console',m=>logs.push(m.text()));page.on('pageerror',e=>logs.push(e.message));for(const [route,name] of [['settings','Settings'],['jobs','Jobs'],['live','Live'],['recordings','Sign in']]){await page.goto(`${origin}/app/${route}`);
  await page.getByRole('heading',{name}).waitFor()}const html=await (await page.request.get(origin+'/app/')).text();const asset=/src=\"(\/app\/assets\/[^\"]+\.js)\"/.exec(html)[1];const bundle=await (await page.request.get(origin+asset)).text();
  assert.equal(/eufy-security-client|OPENAI_API_KEY|\/v1\/chat\/completions/.test(bundle),false);
  assert.equal((await page.request.get(origin+'/api/v1/contract')).status(),200);
  assert.equal((await page.request.get(origin+'/api/v1/jobs/no/artifacts/no')).status(),404);
  await page.goto(origin+'/app/recordings');
  await page.getByLabel('Email').fill('fail@test');
  await page.getByLabel('Password').fill('secret');
  await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByText(/Could not complete login/i).waitFor();
  await page.getByLabel('Email').fill('x@test');
  await page.getByLabel('Password').fill('secret');
  await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByLabel('Verification code').fill('bad');
  await page.getByRole('button',{name:'Verification code'}).click();
  await page.getByText(/incorrect/i).waitFor();
  assert.match(page.url(),/recordings/);
  await page.getByLabel('Verification code').fill('captcha');
  await page.getByRole('button',{name:'Verification code'}).click();
  await page.getByAltText('CAPTCHA challenge').waitFor();
  await page.getByLabel('Verification code').fill('123456');
  await page.getByRole('button',{name:'Verification code'}).click();
  await page.getByRole('button',{name:'Refresh inventory'}).waitFor();
  await page.getByRole('button',{name:'Refresh inventory'}).click();
  await page.getByRole('status').getByText(/device discovery failed/i).waitFor();
  await page.getByRole('button',{name:'Sign out'}).click();const logoutDialog=page.getByRole('alertdialog');
  await logoutDialog.waitFor();
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Close');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Sign out');
  await page.waitForTimeout(1400);
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Sign out');
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Close');
  await page.keyboard.press('Escape');
  assert.equal(await logoutDialog.count(),0);
  await page.waitForFunction(()=>document.activeElement?.textContent==='Sign out');
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Sign out');
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByRole('alertdialog').getByRole('button',{name:'Close'}).click();
  await page.waitForFunction(()=>document.activeElement?.textContent==='Sign out');
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Sign out');
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByRole('alertdialog').getByRole('button',{name:'Sign out'}).click();
  await page.getByRole('heading',{name:'Sign in'}).waitFor();
  assert.equal(logins,2);const stored=await page.evaluate(()=>[...Object.keys(localStorage).map(k=>k+'='+localStorage.getItem(k)),...Object.keys(sessionStorage).map(k=>k+'='+sessionStorage.getItem(k))].join('&'));
  assert.equal(stored.includes('secret'),false);
  assert.equal(stored.includes('bad'),false);
  assert.equal(page.url().includes('secret'),false);
  assert.equal(logs.join('\n').includes('secret'),false);
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('button',{name:'Live'}).click();
  assert.match(page.url(),/\/app\/live/);
  await page.goBack();
  await page.getByRole('heading',{name:'Sign in'}).waitFor();
  assert.equal(await page.locator('.sheet-sidebar').count(),0);
  await page.getByRole('button',{name:'Open navigation'}).focus();
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>Boolean(document.querySelector('.sidebar')?.contains(document.activeElement))),false);const menu=page.getByRole('button',{name:'Open navigation'});
  await menu.focus();
  await page.keyboard.press('Enter');
  await page.locator('.sheet-sidebar').waitFor();
  assert.equal(await page.evaluate(()=>document.querySelector('.sheet-sidebar')?.contains(document.activeElement)),true);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('.sheet-sidebar'));
  assert.equal(await page.locator('.sheet-sidebar').count(),0);
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Open navigation');
  assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Open navigation');
  await page.keyboard.press('Enter');
  await page.locator('.sheet-sidebar').getByRole('button',{name:'Close'}).click();
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Open navigation');
  assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Open navigation');
  await page.keyboard.press('Enter');
  await page.locator('.sheet-sidebar').waitFor();
  assert.equal(await page.evaluate(()=>document.querySelector('.sheet-sidebar')?.contains(document.activeElement)),true);
  await page.getByRole('button',{name:'Assistant'}).click();const dialog=page.getByRole('dialog',{name:'Assistant'});
  await dialog.waitFor();const assistantClose=dialog.getByRole('button',{name:'Close'});assert.equal(await assistantClose.isVisible(),true);assert.equal(await assistantClose.isEnabled(),true);const closeBox=await assistantClose.boundingBox();assert.ok(closeBox&&closeBox.x>=0&&closeBox.y>=0&&closeBox.x+closeBox.width<=390&&closeBox.y+closeBox.height<=844);assert.equal(await page.getByRole('button',{name:'Open navigation'}).count(),0);assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Close');
  await page.keyboard.press('Tab');
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Close');
  await page.keyboard.press('Escape');
  assert.equal(await dialog.count(),0);
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Open navigation');
  assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Open navigation');
  await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'Assistant'}).click();
  await page.getByRole('dialog',{name:'Assistant'}).getByRole('button',{name:'Close'}).click();
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Open navigation');
  assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Open navigation');
  await page.setViewportSize({width:1440,height:900});
  await page.goto(origin+'/app/settings');
  await page.getByRole('heading',{name:'Settings'}).waitFor();const before=await page.locator('.sidebar').evaluate(e=>e.getBoundingClientRect().width);
  await page.locator('.collapse').click();
  assert.ok(await page.locator('.sidebar').evaluate(e=>e.getBoundingClientRect().width)<before);
  assert.equal(logs.some(x=>/secret|bad|captcha|123456/i.test(x)),false);});
test('Chromium shows restored and expired resident sessions without a login replay',async t=>{for(const [valid,phrase] of [[true,'Connected'],[false,'Sign in']]){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eufy-pw-restore-'));let restoreCalls=0,loginCalls=0;const session={authenticated:valid,state:{phase:valid?'connected':'login_required',devices:[],diagnostics:[],message:valid?'connected':'expired',messageI18n:{key:valid?'service.devices.empty':'service.auth.expired',params:{country:'CA'}}},isAuthenticated(){return this.authenticated},async restore(){restoreCalls++},async login(){loginCalls++},async refresh(){if(valid)throw Object.assign(new Error('expired'),{i18n:{key:'service.auth.expired'}})},fail(error){this.authenticated=false;this.state={phase:'login_required',devices:[],diagnostics:[],message:'expired',messageI18n:error.i18n}},close(){}};const srv=createServer({port:0,session,recordings:{close(){}},outputRoot:root});
  await new Promise(r=>srv.start(r));let b;try{b=await chromium.launch({headless:true});const page=await b.newPage();
  await page.goto(`http://127.0.0.1:${srv.address().port}/app/recordings`);
  await page.getByRole('heading',{name:phrase}).waitFor();
  assert.equal(session.authenticated,valid);
  assert.equal(restoreCalls,1);
  assert.equal(loginCalls,0);
  await page.getByRole('status').getByText(valid?/empty device list/i:/session has expired/i).waitFor();if(valid){await page.getByRole('button',{name:'Refresh inventory'}).click();
  await page.getByRole('heading',{name:'Sign in'}).waitFor();
  await page.getByRole('status').getByText(/session has expired/i).waitFor()}}finally{if(b)await b.close();
  await new Promise(r=>srv.close(r));
  await srv.shutdown();fs.rmSync(root,{recursive:true,force:true})}}});
test('Chromium preserves explicit language, tolerates denied storage, and localizes later reachability failure',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'eufy-pw-pref-'));const session={authenticated:false,state:{phase:'login_required',devices:[],diagnostics:[],message:'登录'},close(){}};const srv=createServer({port:0,session,recordings:{close(){}},outputRoot:root});await new Promise(r=>srv.start(r));const origin=`http://127.0.0.1:${srv.address().port}`;let browser;t.after(async()=>{if(browser)await browser.close();await new Promise(r=>srv.close(r));await srv.shutdown();fs.rmSync(root,{recursive:true,force:true})});browser=await chromium.launch({headless:true});const en=await browser.newContext({locale:'zh-CN'});await en.addInitScript(()=>localStorage.setItem('eufy-agent-hub.language','en'));const page=await en.newPage();await page.goto(origin+'/app/recordings');await page.getByRole('heading',{name:'Sign in'}).waitFor();assert.equal(await page.getByLabel('Language').inputValue(),'en');await page.reload();assert.equal(await page.getByLabel('Language').inputValue(),'en');await page.getByLabel('Language').selectOption('zh-CN');await page.route('**/status',route=>route.abort());await page.waitForFunction(()=>document.body.textContent?.includes('无法连接本地服务。'));await en.close();const denied=await browser.newContext({locale:'zh-CN'});await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('denied')}}));const deniedPage=await denied.newPage();await deniedPage.goto(origin+'/app/recordings');await deniedPage.getByRole('heading',{name:'登录'}).waitFor();assert.equal(await deniedPage.getByLabel('语言').inputValue(),'zh-CN');assert.equal(await deniedPage.evaluate(()=>document.documentElement.classList.contains('dark')),false);await denied.close();});
